apiVersion: apps/v1
kind: Deployment
metadata:
  name: napp
  labels:
    app: napp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: napp
  template:
    metadata:
      labels:
        app: napp
    spec:
      containers:
      - name: napp
        image: shailadocker123/nodeapp:v1
        ports:
        - containerPort: 3000
